[window]
dynamic_title = true
padding = { x = 8, y = 8 }
opacity = 0.90

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l", "-i"]    # login & interactive so it reads ~/.zshrc



[scrolling]
history = 10000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 0
color = "0xff1744"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold   = { family = "JetBrains Mono", style = "Bold" }
size = 11.0
offset = { x = 0, y = -1 }

[cursor]
style = "Beam"
vi_mode_style = "Beam"

[colors.primary]
background = "0x1e1e1e"
foreground = "0xffffff"

[colors.cursor]
text = "0x1e1e1e"
cursor = "0xf4b400"

[colors.normal]
black = "0x1e1e1e"
red = "0xff6f00"
green = "0xf4b400"
yellow = "0xff9100"
blue = "0xff1744"
magenta = "0xff9100"
cyan = "0xf4b400"
white = "0xffffff"

[colors.bright]
black = "0xaaaaaa"
red = "0xff6f00"
green = "0xf4b400"
yellow = "0xff9100"
blue = "0xff1744"
magenta = "0xff9100"
cyan = "0xf4b400"
white = "0xeeeeee"

