# Minimal Powerlevel10k config for Orange Cracker
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MODE=nerdfont-complete

# Colors
typeset -g POWERLEVEL9K_DIR_FOREGROUND=166
typeset -g POWERLEVEL9K_DIR_BACKGROUND=0
typeset -g POWERLEVEL9K_VCS_FOREGROUND=208
typeset -g POWERLEVEL9K_VCS_BACKGROUND=0
